---
apiVersion: v1
kind: Secret
metadata:
  name: 'example-galaxy-external-database'
stringData:
  host: 'galaxy-postgresql'
  port: '5555'
  database: 'galaxy'
  username: 'galaxy'
  password: 'galaxy'
  sslmode: 'prefer'
  type: 'unmanaged'
type: Opaque
